name: kenley Gard
favicon: null
layout_spectrum: 0.34109
typography_spectrum: 0.31648
title: Folio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1114'
    - '#e5f4fb'
    - '#6b8fc3'
    - '#51504b'
    - '#af9274'
  brandStrength: 0.6725485445931554
  lightness: 0.6875
  saturation: 0.37701883842237294
  rhythmicContrast: 0.5948881804943085
purpose: []
